### ISSUE TITLE
Entries are hidden when a config setting changed

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#120]
When changing the config (ex: alinea.config.tsx), the existing entries are not visible anymore. Refreshing the page is not solving this issue. For now you need to restart the alinea serve command.

![entries_removed_when_config_changed](https://user-images.githubusercontent.com/1882256/171853445-e15b9524-0073-4f3c-94a3-95fd229a09a9.gif)

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
