### ISSUE TITLE
select: initialvalue not set in json data

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#122]
When an initialvalue is set within a select, the value is displayed within the entry after creating it, but the auto selected value is not saved within the json data file.

```
country: select('Country', {
  BE: 'Belgium'
}, {
  initialValue: 'BE'
})
```

The `country` key is not set within the json data file after publising the entry.

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
