### ISSUE TITLE
Ordening entries creates hidden drafts

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#124]
When you orden an entry to another place, it secretly creates a new draft.
The new created draft is not indicated by a draft number (on the drafts icon).

It would be better to publish the entry immediately when it was published before or that the draft icon indicates that a new draft was created.

Screen of the problem:
![sorting_creates_draft_versions](https://user-images.githubusercontent.com/1882256/172331344-e4742dd5-9c25-4fce-b227-c767cf027784.gif)

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
