### ISSUE TITLE
New entry: remove type field from the view when there's only one option

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#147]
Remove the type field from the view when there's only one option:

![image](https://user-images.githubusercontent.com/1882256/173021373-33d4ed97-09ac-4f98-9f71-2c84c85c962f.png)

**Comment by chetanverma16** [comment]
Hey @cloetensbrecht,
I would like to work on this.
Is there any documentation to setup the repo locally?

**Comment by benmerckx** [comment]
@chetanverma16 you can find some instructions here: https://github.com/alineacms/alinea/blob/main/contributing.md

Another thing here is we'll want to correctly handle the case where there are no options. When setting up a new Root it's easy to forget to define the Types it can contain and currently this results in an error.
