### ISSUE TITLE
Checkbox: optional option

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#151]
![image](https://user-images.githubusercontent.com/1882256/173032722-108aad27-32d4-45cb-80d3-9a92fee47d47.png)

It's a little strange to have an optional optional option. Because this option is optional it inidcates that when this option is not present this field is required. In this case a checkbox is always required to be checked when the optional option is not present (by default). I believe it's better to replace it by a required option to mark it as 'required to be checked'. Otherwise it seems that the checkbox is not valid when it's not checked.

**Comment by benmerckx** [comment]
Will move to `required` in #369
