### ISSUE TITLE
List with lots of richTexts is loading slow(er)

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#164]
When you have a list with a richText inside it and you fill the data with lost of list items, it every time generates the richText. Because of this, rendering all entered richText data seems to go slow when loading the view. It would be better to render them only when they are visible in the view (lazyload).

Playground: https://alinea.sh/playground#code/aW1wb3J0IHsKICB0eXBlLAogIGxpc3QsCiAgc2NoZW1hLAogIHJpY2hUZXh0Cn0gZnJvbSAnYWxpbmVhJwoKZXhwb3J0IGRlZmF1bHQgdHlwZSgnVHlwZScsIHsKICBkZXRhaWxzOiBsaXN0KCdEZXRhaWxzJywgewogICAgc2NoZW1hOiBzY2hlbWEoewogICAgICBkZXRhaWw6IHR5cGUoJ0RldGFpbCcsIHsKICAgICAgICBkZXNjcmlwdGlvbjogcmljaFRleHQoJ0Rlc2NyaXB0aW9uJykKICAgICAgfSkKICAgIH0pCiAgfSkKfSk=

Add a lot of details to it with some "Lorem Ipsum" data. When loading the page, rendering will be slow (difficult to test on the playground because the data is rendered while adding it, but when it's loaded from the json data file, you can see the problem).

**Comment by benmerckx** [comment]
Can you check if this is still an issue with 0.5.12?
