### ISSUE TITLE
Unexpected token A in JSON at position 0 when publishing entries

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#187]
Difficult to replicate, but somethimes I receive an error after publishing an entry.

![image](https://user-images.githubusercontent.com/1882256/178041629-878893f9-9552-4124-95ae-0bdc6f3d6b8c.png)
![image](https://user-images.githubusercontent.com/1882256/178041828-2751696d-0418-44e2-b24c-5277464a8f53.png)

Restarting alinea serve is the only solution to fix the error.

**Comment by benmerckx** [comment]
This was #196, more info is logged to the terminal now if anything happens during serve process
