### ISSUE TITLE
Add <small> tag to the WYSIWYG editor

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#192]
It would be nice to have an option to add `<small>` tags to the WYSIWYG editor.

Expected result:
`<p><small>This is small text</small></p>`

![image](https://user-images.githubusercontent.com/1882256/178830770-41f12325-ae82-4c47-a8e2-d32ab7db524d.png)

**Comment by benmerckx** [comment]
Could we come up with an api that make these configurable? Something like

````ts
richText('My text field', {
  formats: [
    {
      label: 'Small text',
      tag: <small />
    }
  ]
})
````

**Comment by cloetensbrecht** [comment]
Sure, but maybe it's not a fromat but more something like bold, italic, ... :)
