### ISSUE TITLE
Undo (Ctrl+Z) not working

### ISSUE THREAD

**Issue by ValerieCodeurs** [alineacms/alinea#207]
When editing an entry it's not possible to undo changes with Ctrl+Z.

**Comment by benmerckx** [comment]
Should be provided by https://tiptap.dev/api/extensions/collaboration however it clearly doesn't work. Might have to debug what happens here: 
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-collaboration/src/collaboration.ts#L95-L101
