### ISSUE TITLE
UI published / draft / ...

### ISSUE THREAD

**Issue by StijnVanDoorslaer** [alineacms/alinea#222]
- Settings icon -> publish icon
- Select (unpublish, delete)

![27-07-2022-04-20-20](https://user-images.githubusercontent.com/11063619/182624297-d6a18b03-501b-4243-95c3-4cba4f68f21a.png)

**Comment by dmerckx** [comment]
https://www.figma.com/file/cr6yElmcqnF4ApgX6n8K65/Alinea---UI-published-draft?node-id=0%3A1&t=0FNsw31BQYm4uebR-1

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
