### ISSUE TITLE
Duplicate references

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#225]
Don't know the exact reason, but after creating, editing, publishing, moving, .. entries, the references are multiplied:

![image](https://user-images.githubusercontent.com/1882256/183052481-d0bd793d-dad9-4e9a-8898-fc299ede1521.png)

**Comment by benmerckx** [comment]
This is only in the "select a reference" modal? Or also in the sidebar?

**Comment by cloetensbrecht** [comment]
Before it was also in the sidebar. But i think it was fixed in a previous release. The current problem appears in the "select a reference" modal.
