### ISSUE TITLE
Multiple link is reacting as a single select when no max property is set

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#226]
The following setting is resulting in a single select, even when multiple is set to true:

```
project: link('Project', {
	type: 'entry',
	multiple: true,
	optional: false,
	condition: Entry.type.is('Project')
}),
```

Entering a max property is solving this issue, but I would expect that the max property is not required because the multiple property was set to true already.

```
project: link('Project', {
        type: 'entry',
        multiple: true,
        max: 10,
        optional: false,
        condition: Entry.type.is('Project')
}),
```

**Comment by cloetensbrecht** [comment]
This issue still exists. In v 0.2 it's even not working with the max property anyymore:

```
estimate: link('Estimate', {
      type: 'entry',
      multiple: true,
      optional: true,
      condition: Entry.type.is('Estimate'),
      width: 0.5
}),
```

**Comment by benmerckx** [comment]
You can use alinea.link.multiple(...). I guess it would be best to remove multiple from the options and improve docs :) If you're only after entries use alinea.entry.multiple(...)

**Comment by benmerckx** [comment]
Multiple is no longer a part of the options in 0.4.0 but we do still need to update the docs
