### ISSUE TITLE
Not possible to empty a number field when an initialValue is set

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#236]
When a number field has an initialValue it is not possible to empty the field, even when it is marked as optional.
Because the field is optional it should be possible to empty the value. The initialvalue should only put a value on the first render, not after a change.

```
price: number('Price', {
        optional: true,
        initialValue: 100
})
```

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
