### ISSUE TITLE
Remove auto scroll when navigating to alinea.sh

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#249]
When navigating to https://alinea.sh the page will automatically scroll to the demo section. This is very annoying. Keep the page at the top. If you want to highligt the demo section, make the Demo navigation more remarkable by making a purple button from it.

![image](https://user-images.githubusercontent.com/1882256/187615502-1d64dfa7-d771-453e-9acf-4594c2749113.png)

**Comment by benmerckx** [comment]
For anyone who'd like to look into this, I'm pretty sure this happens because the tip tap editor used in input.richtext has a scrollIntoView call somewhere which we would need to disable.
