### ISSUE TITLE
After manually undoing a change, draft remains

### ISSUE THREAD

**Issue by ValerieCodeurs** [alineacms/alinea#264]
To reproduce change an entry. For example,
![image](https://user-images.githubusercontent.com/86597952/192285411-da0aa00d-d464-4b72-acb8-159e6925ccfe.png)

After undoing the change manually (not with 'discard' button) the entry is still listed as draft.
![image](https://user-images.githubusercontent.com/86597952/192285829-caedca8e-2ca5-4d2f-951e-fd06bc3c7f67.png)

**Comment by benmerckx** [comment]
The draft workflow has been reworked in our latest release. While undoing a single edit will still show up as a change I think it's acceptable for now. A lot of software works the same way, so it's not exactly unexpected.
