### ISSUE TITLE
TypeError in Processing fields

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#276]
The process function is resulting the following TypeScript error:

> Property 'process' does not exist on type 'Expr<string>'.ts(2339)

Usecase:
``` TypeScript
const rows = await pages.whereRoot('clients').whereType('Client').select(client => ({
   url: client.url.process(url => `/clients${url}`)
}))
```

The usecase is based on the example coming from 'Processing fields' at https://alinea.sh/docs/content/pages

**Comment by benmerckx** [comment]
This is no longer relevant in our latest release. We've decided to drop the process method from the api.
