### ISSUE TITLE
Provide support for nextjs13 server components

### ISSUE THREAD

**Issue by dmerckx** [alineacms/alinea#277]
I can't seem to use the pages api from my server component:
![03-11-2022-04-48-07](https://user-images.githubusercontent.com/2300429/199768429-5177545f-5a1c-470e-977a-325cc53e2c7a.png)

This is my setup:
![03-11-2022-04-48-13](https://user-images.githubusercontent.com/2300429/199768451-e93bd32f-cb92-4f53-b36c-bb0d7878537d.png)

**Comment by dmerckx** [comment]
Latest version has support, but is now lacking a way to create previews.

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
