### ISSUE TITLE
Media upload does not work

### ISSUE THREAD

**Issue by jide** [alineacms/alinea#278]
When choosing a media, the media preview shows up in the left sidebar, but then nothing happens, there is no way to upload the image. Confirm does nothing neither.

![image](https://user-images.githubusercontent.com/333073/202406044-98fe010d-c5eb-46ba-b3d9-c189a61fc81f.png)

**Comment by benmerckx** [comment]
Thank you for logging. Media management has been reworked and this is fixed in our latest release 0.4.0
