### ISSUE TITLE
Single select input returns an array within the Typescript output instead of a string

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#282]
![image](https://user-images.githubusercontent.com/1882256/205480273-3cb2751d-0cc3-4ffc-8c2c-4924f4e142af.png)

Temporary workaround:
`invoice.status as unknown as Page.Invoice['status'][number]`

**Comment by benmerckx** [comment]
This is fixed in f1c3987a9a43e9a158ed990311c0d7d90af82ec5, but not released yet
