### ISSUE TITLE
CTRL + S is resulting in a disconnected server error message

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#285]
When you edit an entry and want to save (draft or publish) it by pressing `CTRL` `S`, it's resulting in a disconnected server error message:

![image](https://user-images.githubusercontent.com/1882256/207809965-dd9bce73-6640-4092-8844-1898b024ee45.png)

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
