### ISSUE TITLE
When browsing to alinea.sh/roadmap json is returned

### ISSUE THREAD

**Issue by ValerieCodeurs** [alineacms/alinea#290]
![image](https://user-images.githubusercontent.com/86597952/208443946-2517db39-0e35-42f5-9746-6481c8c6a679.png)

**Comment by dmerckx** [comment]
Saw the same thing for the blog page just now:
![image](https://user-images.githubusercontent.com/2300429/215888547-d6b7de9d-67f9-4974-bd57-1ef70fbc4d62.png)

Might be an exotic nextjs issue. We should probably update to latest version and check if it still occurs.

**Comment by benmerckx** [comment]
Seems to be resolved since recent redeployment. I'm going to assume this was on Vercel's side.

**Comment by benmerckx** [comment]
Oops, nope still going on

**Comment by benmerckx** [comment]
Upgrading the site next 13 fixed this
