### ISSUE TITLE
UI is opening the wrong entry modal

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#300]
When there are nested entries and you want to add a new entry within a nested entry, it's opening the modal of the parent entry when it's selected. Difficult to explain, but maybe the following video will make the problem clear:

![add_entry_issue](https://user-images.githubusercontent.com/1882256/215132881-c1bc7f1a-95d9-42b3-8e65-c87b3a00729a.gif)

(+) next to Estimates should open a modal with the possibility to add an EstimateFolder.
(+) next to 2023 should open a modal with the possibility to add a new Extimate.
Buth when Estimates is selected, clicking the (+) next to 2023 is triggering the (+) of the selected Estimates entry.
This error also occures in the opposit direction, when 2023 is selected and you click the (+) next to the Estimates entry.

**Comment by benmerckx** [comment]
This is fixed in 0.4.0. There's a single button to create new entries which picks the parent you're currently in
