### ISSUE TITLE
Selecting a page is opening the page instead of selecting the page

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#301]
When you click on the name of a page within the page selector modal, than you're navigating to the selected page instead of selecting the page.
Expected behaviour: mark the checkbox and select the page.

![select_page](https://user-images.githubusercontent.com/1882256/215138316-0a8ea9a7-1889-48c7-a9a2-3d5d89d6ee62.gif)

**Comment by benmerckx** [comment]
This is fixed in 0.4.0
