### ISSUE TITLE
process is undefined within cms.ts

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#319]
When using a process.Env variable within the cms.ts file, we're receiving the following error:  
`Uncaught (in promise) ReferenceError: process is not defined`
The error is not present within the debug console of vscode, it's only present within the browser console when running  
`alinea serve -- next dev`

Alinea version: 0.4.0-preview.30

Code example of cms.ts:
```
import { home } from '@/channels/home.channel'
import { page } from '@/channels/page.channel'
import alinea, {createCMS} from 'alinea'

export const cms = createCMS({
  schema: {
    Home: home,
    Page: page
  },
  workspaces: {
    main: alinea.workspace('Example', {
      pages: alinea.root('Example', {
        home: alinea.page(
          home({
            title: 'Home'
          })
        ),
        [alinea.meta]: {
          contains: process.env.APP_ENV === "production"
            ? ["Page"]
            : ["Page", "Home"]
        }
      }),
      media: alinea.media(),
      [alinea.meta]: {
        source: 'content',
        mediaDir: 'public'
      }
    })
  }
})
```

**Comment by benmerckx** [comment]
Alinea exposes only NODE_ENV and variables that are commonly accepted on the client: anything starting with NEXT_PUBLIC_, PUBLIC_, VITE_ or GATSBY_. However the dashboard should not fail to load. In a newer version this will log a warning in the console but continue the dashboard to load.
