### ISSUE TITLE
Creating a sub entry is not appearing in the left navigation pane

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#322]
When you create a child entry within a container entry, it's not appearing at the left navigation pane.

Alinea version: ^0.4.0-preview.30

Ex:
```
// News entry
export const NewsSchema = alinea.type('News', {
  title: alinea.text('Title'),
  path: alinea.path('Path', {
    hidden: true,
    readonly: true
  }),
  [alinea.type.meta]: {
    isContainer: true,
    contains: ['Newsdetail']
  }
})

// News detail entry
export const NewsdetailSchema = alinea.type('News detail', {
  title: alinea.text('Title', {width: 0.5}),
  path: alinea.path('Path', {width: 0.5})
})
```

When creating a news detail within the News entry, the new entry is displayed at the right detail pane, but it's not appearing at the left navigation pane. You need to refresh the page before it appears.

![bug-new-sub-entry](https://github.com/alineacms/alinea/assets/1882256/e90d9cf1-60a2-48b4-8e17-54f65cbd1f76)

**Comment by benmerckx** [comment]
Fixed in 0ae47e5ea1b76017bb4ea2e9bf6f785f4c253cb2
