### ISSUE TITLE
Roots: Improve the docs - the structure of the properties are not correct in the examples

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#343]
URL: https://alinea.sh/docs/configuration/root

For now it's not clear that the icon, contains and i18n properties should be nested within an [alinea.meta] property.
The example would be more clear when it's displayed like this:

``` typescript
alinea.root('My root', {
	[alinea.meta]: {
		icon, contains, i18n
	}
})
```

The docs are also not specifying how to add the seeders. The seeders should also be added to the examples and needs to be written inside the docs:

``` typescript
alinea.root('My root', {
	pageSeeder1,
	pageSeeder2,
	[alinea.meta]: {
		icon, contains, i18n
	}
})
```

Even better would be that you can see the full code of each variable:

``` typescript
import alinea from "alinea"
import { IcRoundCheck } from "alinea/ui/icons/IcRoundCheck"

const pageSeeder1 = alinea.page() // not clear how to make a seeder
const pageSeeder2 = alinea.page() // not clear how to make a seeder
const icon = IcRoundCheck
const contains = ['Page']
const i18n = {
	locales: ['en', 'fr', 'nl']
}

alinea.root('My root', {
	pageSeeder1,
	pageSeeder2,
	[alinea.meta]: {
		icon, contains, i18n
	}
})
```

**Comment by benmerckx** [comment]
Seeding is undocumented for now until it is stable. The options are updated in the example.
