### ISSUE TITLE
CMS config: Inconsistent use of naming conventions

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#346]
Within the CMS config, you can add a `schema` and a `workspaces` property.
Both can accept multiple schemas/workspaces. It would be logic to rename the `schema` property into `schemas` as it can contain multiple schemas just like workspaces can contain multiple workspaces.

```typescript
export const cms = createNextCMS({
  dashboard, preview, schemas, workspaces
})
```

Also place the different properties in alphabetical order. The same order should be used within the documentation which will make is more easy for a user to find the things they need.

**Comment by benmerckx** [comment]
A Schema is a collection of multiple Types. I suppose it could have been named "types", but "schemas" makes no sense as there can only be one schema per config.

**Comment by benmerckx** [comment]
Tried to make this a bit more clear in the docs... https://alinea.sh/docs/configuration/schema
