### ISSUE TITLE
Number field: impossible to place a 0 after the decimal point

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#363]
It's impossible to write a decimal number like 0,05. When entering a 0 after the decimal point, it's removed automatically.

```typescript
{
  amount: alinea.number("Amount"),
}
```

![number_leading_zero](https://github.com/alineacms/alinea/assets/1882256/c0b8a2d0-396b-4eac-b18b-9b367aeb03f4)

**Comment by benmerckx** [comment]
The number field now accepts whatever the browser accepts. I notice in Chrome decimal numbers are formatted by locale, so 0,05 is a valid input there.
