### ISSUE TITLE
Collection config style

### ISSUE THREAD

**Issue by benmerckx** [alineacms/alinea#373]
Do we really need [alinea.meta] style configuration or can we get away with 3 arguments for constructors that are typically a collection of other things such as Type, Schema etc? By extension also Workspaces, Roots and even Link and Select field. We can still support the symbol for some time for backwards compatibility.

**Comment by cloetensbrecht** [comment]
Personally I only use the icon and the contains property a lot. I'm not using the [alinea.meta] style configuration for any other reason. When you would remove the alinea.meta property, we still should be able to add an icon or define the allowed sub Schemas somewhere else :) But Some other options should be available to:
- Limit the total of sub entries. Ex: only 5 sub entries are allowed
- Limit the usage of a specific sub Schema: Ex: An Overview page can be added only once.
- Limit the rights of a Schema to a specific user or user role
- ...
So probably we will still need some kind of configuartion property to define all kind of things that will be added in future.

**Comment by benmerckx** [comment]
This issue is not about removing the options entirely but moving things around so we have consistent "syntax" to define configuration. The issue should be clear when we compare for example the way to define a type vs a select field vs a list:

````tsx
alinea.type('My type', {
  // field collection,
  [alinea.meta]: {
    // options
  }
})

alinea.select('Select field', {
  // option collection
}, {
  // options
})

alinea.list('List field', {
  schema: {
    // type collection
  },
  // options
})
````

Having three different ways of achieving the same thing is not very intuitive. It could be changed to:

````tsx
alinea.type('My type', {
  fields: {
    // field collection
  },
  // options
})

alinea.select('Select field', {
  options: {
    // option collection
  },
  // options
})

alinea.list('List field', {
  schema: {
    // type collection
  },
  // options
})
````

**Comment by cloetensbrecht** [comment]
I like consistency. Go ahead ! 😍
