### ISSUE TITLE
Explore the possibility to use Github Deploy keys instead of tokens

### ISSUE THREAD

**Issue by dmerckx** [alineacms/alinea#85]
Tokens cant be scoped to a single repo, making them a bigger security risk if they leak.

https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys

**Comment by benmerckx** [comment]
We'll have another look at this when checking out the self-hosted option

**Comment by benmerckx** [comment]
Deploy keys cannot access the github api
